name: Deploy to Lambda
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: Create deployment package
      run: |
        zip -r lambda_test.zip . -x "*.git*" ".github/*" "example_event.json" "test_lambda_function.py"

    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code --function-name lambda_test --zip-file fileb://lambda_test.zip

    - name: Verify deployment
      run: |
        RESPONSE=$(aws lambda get-function --function-name lambda_test)
        echo "Lambda function updated: $RESPONSE"
        echo "LAMBDA_UPDATE_STATUS=success" >> $GITHUB_ENV